controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    # imu_broad:
    #   type: imu_sensor_broadcaster/IMUSensorBroadcaster 


diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint','back_left_wheel_joint']
    right_wheel_names: ['right_wheel_joint','back_right_wheel_joint']
    wheels_per_side: 2
    wheel_separation: 0.36
    wheel_radius: 0.055

    use_stamped_vel: false

# imu_broad:
#   ros__parameters:
#     sensor_name: imu_link  # This should match the name of the IMU link in the URDF
#     frame_id: imu_link
