twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 1
      navigation:
        topic   : cmd_vel_smoothed
        timeout : 0.5
        priority: 1
      obstacle:
        topic   : cmd_vel_obstacle
        timeout : 0.5
        priority: 100

      